### ISSUE TITLE
The program can't start tasks without a poolkey wich isn't needed for portable plots

### ISSUE THREAD

**Issue by Hades2525** [merakmarey/madFurry#1]
Hi. I was testing your program but I can't plot portable plots because it asks for the pool key... Or am I missing something ?
Looking forward for a response.

**Comment by merakmarey** [comment]
madFurry is a GUI/plot manager for madMax plotter, and not a plotter by itself. madMax plotter requires a pool key or a contract address.

**Comment by Hades2525** [comment]
I know that but when I only input a farmer key + a contract adress like this :
![image](https://user-images.githubusercontent.com/79328748/125174810-2bd4b080-e1c8-11eb-8d28-05f5f1ca2359.png)
It gives me this error :
![image](https://user-images.githubusercontent.com/79328748/125174834-4ad34280-e1c8-11eb-8f71-acb2fc8fbe2d.png)

**Comment by zagon-bit** [comment]
I have the same problem

**Comment by merakmarey** [comment]
Just corrected on 0.3. Please update.

**Comment by Hades2525** [comment]
You didn't upload the 0.3. version.
Edit : nevermind.
