### ISSUE TITLE
v0.9 AutoGet button not working correctly

### ISSUE THREAD

**Issue by VivaLaRobo** [merakmarey/madFurry#2]
Chia-Blockchain is running and synced. But when I click on AutoGet it only populates the Farmer Key. It doesn't add in the pool contract address and the "Select from wallet" drop down doesn't have anything in it.

I also noticed the "Suggested" Plot Tasks says 0 no matter what I try. It used to say 1 or 2 but now it only ever says 0.

**Comment by VivaLaRobo** [comment]
Just noticed 0.9 was released, downloading and testing again

**Comment by VivaLaRobo** [comment]
Issue still happens in v0.9

**Comment by merakmarey** [comment]
Plot tasks suggestions works based on free space you have on you Tmp Path # 1.  I'm checking the code to see if there is any miscalculations. If so, it will be corrected and released on 0.9.1, which should be available soon. Also, the issue with AutoGet is already corrected and will also be available on 0.9.1. In the mean time you can type your keys by hand, it won't affect plotting.

**Comment by VivaLaRobo** [comment]
Yeah I just needed to clear the temp folder to fix the issue with the Plot Tasks. 

Something else I noticed was the copy function got stuck waiting at 3% even though the full file was transferred already.

**Comment by VivaLaRobo** [comment]
Just saw 0.9.1 was released, gonna test real quick

**Comment by VivaLaRobo** [comment]
v0.9.1 fixes the issue with AutoGet. Thanks!

I'll create a new issue if I notice the copy transfer function getting stuck again
