### ISSUE TITLE
v0.9.1 randomly quits running after [P1] Table 1 took

### ISSUE THREAD

**Issue by VivaLaRobo** [merakmarey/madFurry#3]
I have been using MadFurry v0.9.1 for a while but just today I noticed the app will just stop running mid-plot normally after the "[P1] Table 1 took" line. 

The logs don't show any errors, I have attached it to this ticket. 
[plot-k32-2021-08-12-09-57-dd24cb96660fcc535b00abfcbcd5a29981d20ef1d8e052ae79c50374f7e03c53.plot.log](https://github.com/merakmarey/madFurry/files/6976496/plot-k32-2021-08-12-09-57-dd24cb96660fcc535b00abfcbcd5a29981d20ef1d8e052ae79c50374f7e03c53.plot.log)

Chia Blockchain 1.2.3

I have recently changed to a new SSD for my temp folders, but I didn't think that would cause any issues.

**Comment by VivaLaRobo** [comment]
Testing the MadMax plotter results in the same issue. So might be related to my SSD rather than MadFurry. Testing some more

**Comment by VivaLaRobo** [comment]
Formatting my SSD to EXFAT instead of NTFS seems to have fixed the issue, at least it's able to get further along with the plot now. Everything I've read online says to use NTFS for the temp SSD drive so not sure why it's not working for me. But I'm fine using EXFAT for now. Might just be something up with the SSD too. I'll close this ticket

**Comment by merakmarey** [comment]
It's not supposed to happened. Unfortunately madMax crashes provide ZERO information on the causes of the crash. I am developing a plotter based on madMax, which will be faster and will have less disk I/O operations, and above all,. will inform on crashes with more details. In the mean time, madFurry 0.9.2 will at least alert of crashes so you know earlier that something is going on.

**Comment by VivaLaRobo** [comment]
Awesome! Looking forward to it. Thank you!
