### ISSUE TITLE
Improper hard drive size reporting

### ISSUE THREAD

**Issue by Mecadguy** [merakmarey/madFurry#4]
Latest version is reporting 404 GB free on empty 16 TB drives.

**Comment by merakmarey** [comment]
madFurry reports USABLE disk space, not total disk space. This is a Windows function, not a proprietary implementation, therefore probably other apps will report the same. Check your disk or use any diagnostic tool to see if it fixes the issue.

**Comment by Mecadguy** [comment]
I figured it out; the issue is that I have multiple drives mounted as NTFS
shares. The hose drive is a 404GB drive. This is more of a windows issue. I
was at first thinking your program was grabbing the wrong drive info, but
with an NTFS share it’s simply grabbing the host drive info, which makes
sense as the individual drives show as folders.

**Comment by merakmarey** [comment]
Figures. For all the information showns only uses drive letter to check, therefore a NTFS folder would not work. Good catch though!
